<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ProCard\Models\Base;

use Colibri\Core\Entity;

/**
 * Entity class for representation table 'categories'
 */
class BaseCategory extends Entity
{

  const TABLE = 'categories';

  const ID = 'categories.id';
  const PARENT_ID = 'categories.parent_id';
  const LEFT_KEY = 'categories.left_key';
  const RIGHT_KEY = 'categories.right_key';
  const DEPTH = 'categories.depth';
  const NAME = 'categories.name';
  const LABEL = 'categories.label';
  const DESCRIPTION = 'categories.short_description';
  const CREATED = 'categories.created';
  const MODIFIED = 'categories.modified';
  const ID_KEY = 'id';
  const PARENT_ID_KEY = 'parent_id';
  const LEFT_KEY_KEY = 'left_key';
  const RIGHT_KEY_KEY = 'right_key';
  const DEPTH_KEY = 'depth';
  const NAME_KEY = 'name';
  const LABEL_KEY = 'label';
  const DESCRIPTION_KEY = 'short_description';
  const CREATED_KEY = 'created';
  const MODIFIED_KEY = 'modified';
  
  /**
   * @var integer
   */
  public $id;
  
  /**
   * @var integer
   */
  public $parentId;
  
  /**
   * @var integer
   */
  public $leftKey;
  
  /**
   * @var integer
   */
  public $rightKey;
  
  /**
   * @var integer
   */
  public $depth;
  
  /**
   * @var string
   */
  public $name;
  
  /**
   * @var string
   */
  public $label;
  
  /**
   * @var string
   */
  public $description;
  
  /**
   * @var string
   */
  public $created;
  
  /**
   * @var string
   */
  public $modified;

  /**
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return integer
   */
  public function getParentId()
  {
    return $this->parentId;
  }

  /**
   * @return integer
   */
  public function getLeftKey()
  {
    return $this->leftKey;
  }

  /**
   * @return integer
   */
  public function getRightKey()
  {
    return $this->rightKey;
  }

  /**
   * @return integer
   */
  public function getDepth()
  {
    return $this->depth;
  }

  /**
   * @return string
   */
  public function getName()
  {
    return $this->name;
  }

  /**
   * @return string
   */
  public function getLabel()
  {
    return $this->label;
  }

  /**
   * @return string
   */
  public function getDescription()
  {
    return $this->description;
  }

  /**
   * @return string
   */
  public function getCreated()
  {
    return $this->created;
  }

  /**
   * @return string
   */
  public function getModified()
  {
    return $this->modified;
  }


  /**
   * @param integer $id
   * @return $this
   */
  public function setId($id)
  {
    $this->id = $id;

    return $this;
  }

  /**
   * @param integer $parentId
   * @return $this
   */
  public function setParentId($parentId)
  {
    $this->parentId = $parentId;

    return $this;
  }

  /**
   * @param integer $leftKey
   * @return $this
   */
  public function setLeftKey($leftKey)
  {
    $this->leftKey = $leftKey;

    return $this;
  }

  /**
   * @param integer $rightKey
   * @return $this
   */
  public function setRightKey($rightKey)
  {
    $this->rightKey = $rightKey;

    return $this;
  }

  /**
   * @param integer $depth
   * @return $this
   */
  public function setDepth($depth)
  {
    $this->depth = $depth;

    return $this;
  }

  /**
   * @param string $name
   * @return $this
   */
  public function setName($name)
  {
    $this->name = $name;

    return $this;
  }

  /**
   * @param string $label
   * @return $this
   */
  public function setLabel($label)
  {
    $this->label = $label;

    return $this;
  }

  /**
   * @param string $description
   * @return $this
   */
  public function setDescription($description)
  {
    $this->description = $description;

    return $this;
  }

  /**
   * @param string $created
   * @return $this
   */
  public function setCreated($created)
  {
    $this->created = $created;

    return $this;
  }

  /**
   * @param string $modified
   * @return $this
   */
  public function setModified($modified)
  {
    $this->modified = $modified;

    return $this;
  }

}