<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ProCard\Models;

class CategoryRepository extends Base\BaseCategoryRepository
{
  // ... write your custom code here
}