<?php

/**
 * Generated By ColibriORM Generator
 * @author Ivan Gontarenko
*/

namespace ProCard\Models;

class ProductRepository extends Base\BaseProductRepository
{
  // ... write your custom code here
}